# Generated by Django 6.0.2 on 2026-02-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('ACAO', 'Ação'), ('FII', 'Fundo Imobiliário'), ('Cripto', 'Criptomoeda'), ('RF', 'Renda Fixa'), ('FUNDO', 'Fundo de Investimento')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('cotacao_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('DIVIDENDO', 'Recebimento de Dividendo')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=15)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('custos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investimentos.ativo')),
                ('carteira_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.carteira')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
